INSERT INTO `Airline` (`idAirline`, `name`) VALUES (1, 'Frontier');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (2, 'Virgin America');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (3, 'Delta');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (4, 'Southwest');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (5, 'JetBlue');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (6, 'Hawaiian');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (7, 'Air India');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (8, 'IndiGo');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (9, 'SpiceJet');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (10, 'Vistara');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (11, 'GoAir');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (12, 'AirAsia India');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (13, 'TruJet');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (14, 'Air India Express');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (15, 'Alliance Air');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (16, 'SpiceXpress');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (17, 'Air Deccan');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (18, 'Air Odisha');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (19, 'AirAsia X');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (20, 'Air Carnival');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (21, 'Air Costa');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (22, 'Air India Regional');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (23, 'Air Pegasus');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (24, 'Air Sahara');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (25, 'AirAsia Berhad');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (26, 'Blue Dart Aviation');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (27, 'Club One Air');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (28, 'Deccan Charters');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (29, 'FlyBig');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (30, 'GMR Aviation');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (31, 'Himalaya Airlines');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (32, 'IndiGo Cargo');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (33, 'Jagson Airlines');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (34, 'Manta Air');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (35, 'Mehair');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (36, 'Pinnacle Air');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (37, 'Quikjet Cargo');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (38, 'Safi Airways');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (39, 'Star Air');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (40, 'TajAir');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (41, 'Taneja Aerospace and Aviation');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (42, 'Titan Aviation');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (43, 'Trujet Air');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (44, 'Turbo Megha Airways');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (45, 'Vistara Cargo');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (46, 'Zoom Air');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (47, 'Air Carnival');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (48, 'FlyBig');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (49, 'Air Heritage');
INSERT INTO `Airline` (`idAirline`, `name`) VALUES (50, 'Air Mantra');

