INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (1, 'Indira Gandhi International Airport', 1041);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (2, 'Chhatrapati Shivaji Maharaj International Airport', 1015);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (3, 'Kempegowda International Airport', 1016);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (4, 'Rajiv Gandhi International Airport', 1024);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (5, 'Chennai International Airport', 1045);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (6, 'Netaji Subhas Chandra Bose International Airport', 1023);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (7, 'Kempegowda International Airport', 1025);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (8, 'Dabolim Airport', 1040);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (9, 'Rajiv Gandhi International Airport', 1035);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (10, 'Chhatrapati Shivaji Maharaj International Airport', 1032);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (11, 'Chhatrapati Shivaji Maharaj International Airport', 1023);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (12, 'Indira Gandhi International Airport', 1014);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (13, 'Chhatrapati Shivaji Maharaj International Airport', 1016);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (14, 'Kempegowda International Airport', 1043);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (15, 'Chhatrapati Shivaji Maharaj International Airport', 1027);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (16, 'Indira Gandhi International Airport', 1014);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (17, 'Lal Bahadur Shastri International Airport', 1036);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (18, 'Coimbatore International Airport', 1039);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (19, 'Biju Patnaik International Airport', 1018);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (20, 'Visakhapatnam International Airport', 1022);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (21, 'Trivandrum International Airport', 1038);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (22, 'Goa International Airport', 1042);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (23, 'Madurai International Airport', 1026);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (24, 'Raja Bhoj Airport', 1020);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (25, 'Jolly Grant Airport', 1029);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (26, 'Devi Ahilyabai Holkar International Airport', 1011);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (27, 'Dr. Babasaheb Ambedkar International Airport', 1028);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (28, 'Sri Guru Ram Dass Jee International Airport', 1048);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (29, 'Birsa Munda Airport', 1030);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (30, 'Veer Savarkar International Airport', 1033);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (31, 'Lokpriya Gopinath Bordoloi International Airport', 1031);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (32, 'Mangalore International Airport', 1034);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (33, 'Swami Vivekananda Airport', 1012);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (34, 'Vijayawada International Airport', 1047);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (35, 'Tiruchirappalli International Airport', 1037);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (36, 'Rajahmundry Airport', 1039);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (37, 'Bhavnagar Airport', 1046);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (38, 'Jharsuguda Airport', 1019);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (39, 'Sardar Vallabhbhai Patel International Airport', 1049);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (40, 'Ranchi Airport', 1038);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (41, 'Jaipur International Airport', 1036);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (42, 'Rajkot Airport', 1044);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (43, 'Kochi International Airport', 1026);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (44, 'Ludhiana Airport', 1029);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (45, 'Bagdogra Airport', 1032);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (46, 'Belagavi Airport', 1042);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (47, 'Shri Guru Gobind Singh Ji Airport', 1035);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (48, 'Kushok Bakula Rimpochee Airport', 1040);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (49, 'Rourkela Airport', 1010);
INSERT INTO `Airport` (`idAirport`, `name`, `locID`) VALUES (50, 'Darbhanga Airport', 1027);

