INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1000, 'New York City', 'USA');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1001, 'Tokyo', 'Japan');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1002, 'Mumbai', 'India');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1003, 'Beijing', 'China');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1004, 'Los Angeles', 'USA');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1005, 'Dubrovnik', 'Croatia');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1006, 'Port Louis', 'Mauritius');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1007, 'Nassau', 'Bahamas');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1008, 'Vilnius', 'Lithuania');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1009, 'Matā'utu', 'Wallis and Futuna');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1010, 'Kampala', 'Uganda');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1011, 'Nairobi', 'Kenya');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1012, 'Bujumbura', 'Burundi');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1013, 'Luanda', 'Angola');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1014, 'Castries', 'Saint Lucia');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1015, 'Freetown', 'Sierra Leone');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1016, 'Lagos', 'Nigeria');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1017, 'St. George's', 'Grenada');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1018, 'Longyearbyen', 'Svalbard & Jan Mayen Islands');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1019, 'Phnom Penh', 'Cambodia');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1020, 'Muscat', 'Oman');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1021, 'Kinshasa', 'Congo');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1022, 'Manila', 'Philippines');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1023, 'Christmas Island', 'Australia');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1024, 'Saint-Pierre', 'Saint Pierre and Miquelon');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1025, 'Svalbard', 'Svalbard & Jan Mayen Islands');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1026, 'Kuwait City', 'Kuwait');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1027, 'Yaren', 'Nauru');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1028, 'Brussels', 'Belgium');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1029, 'Manila', 'Philippines');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1030, 'Montevideo', 'Uruguay');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1031, 'Ulaanbaatar', 'Mongolia');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1032, 'Nassau', 'Bahamas');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1033, 'Kyiv', 'Ukraine');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1034, 'N'Djamena', 'Chad');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1035, 'Nuuk', 'Greenland');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1036, 'Saint-Denis', 'Reunion');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1037, 'Tirana', 'Albania');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1038, 'Riga', 'Latvia');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1039, 'Kathmandu', 'Nepal');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1040, 'Sanaa', 'Yemen');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1041, 'Kathmandu', 'Nepal');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1042, 'Podgorica', 'Montenegro');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1043, 'Lusaka', 'Zambia');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1044, 'Kuwait City', 'Kuwait');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1045, 'Beirut', 'Lebanon');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1046, 'Douglas', 'Isle of Man');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1047, 'Basseterre', 'Saint Kitts and Nevis');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1048, 'Plymouth', 'Montserrat');
INSERT INTO `Locations` (`locID`, `city`, `country`) VALUES (1049, 'Banjul', 'Gambia');

