INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1003, 'Airbus A320', 150);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1004, 'Airbus A330', 300);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1005, 'Embraer E190', 114);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1006, 'Boeing 787 Dreamliner', 242);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1007, 'Airbus A380', 853);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1008, 'Bombardier CRJ-900', 90);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1009, 'Cessna 172 Skyhawk', 4);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1010, 'Dassault Falcon 7X', 12);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1011, 'Embraer Phenom 100', 4);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1012, 'Airbus A350', 440);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1013, 'Boeing 767', 181);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1014, 'Cessna Citation X', 12);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1015, 'Embraer E145', 50);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1016, 'Gulfstream G650', 19);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1017, 'Airbus A330neo', 260);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1018, 'Boeing 777', 396);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1019, 'Bombardier Challenger 300', 16);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1020, 'Cessna Citation CJ4', 10);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1021, 'Embraer E175', 80);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1022, 'Airbus A321neo', 240);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1023, 'Boeing 737-800', 189);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1024, 'Cessna Caravan', 14);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1025, 'Dassault Falcon 2000', 19);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1026, 'Gulfstream G550', 19);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1027, 'Airbus A319', 160);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1028, 'Boeing 757', 200);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1029, 'Bombardier Global 6000', 16);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1030, 'Cessna Citation Latitude', 12);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1031, 'Embraer Legacy 450', 9);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1032, 'Airbus A318', 107);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1033, 'Boeing 737-700', 149);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1034, 'Cessna Citation Sovereign', 12);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1035, 'Dassault Falcon 900', 19);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1036, 'Gulfstream G450', 16);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1037, 'Airbus A310', 280);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1038, 'Boeing 737-900ER', 215);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1039, 'Bombardier Learjet 75', 9);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1040, 'Cessna Citation M2', 7);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1041, 'Embraer Legacy 500', 12);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1042, 'Gulfstream G280', 10);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1043, 'Airbus A340', 375);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1044, 'Boeing 737-700ER', 149);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1045, 'Bombardier Learjet 85', 8);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1046, 'Cessna Citation Mustang', 4);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1047, 'Dassault Falcon 50', 9);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1048, 'Embraer Legacy 600', 13);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1049, 'Gulfstream G650ER', 19);
INSERT INTO `PlaneModel` (`idModel`, `name`, `capacity`) VALUES (1050, 'Airbus A330-200', 246);
